# Generated by Django 4.2.30 on 2026-06-27 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VIEW', 'Record Viewed'), ('PAYMENT', 'Fee Payment'), ('MARK_ATTENDANCE', 'Attendance Marked'), ('GRADE_SUBMISSION', 'Submission Graded'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('model_name', models.CharField(blank=True, help_text='The model/resource that was affected.', max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected object.', null=True)),
                ('description', models.TextField(help_text='Human-readable description of what happened.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
