# Generated by Django 4.2.30 on 2026-07-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VIEW', 'Record Viewed'), ('PAYMENT', 'Fee Payment'), ('MARK_ATTENDANCE', 'Attendance Marked'), ('GRADE_SUBMISSION', 'Submission Graded'), ('ASSIGN_MARKS', 'Marks Assigned'), ('OTHER', 'Other')], default='OTHER', help_text='Type of action performed.', max_length=50)),
                ('model_name', models.CharField(help_text='Model/Table name (e.g. Student, Exam, Marks).', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object affected.')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object (for display).', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what happened.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action happened.')),
                ('user', models.ForeignKey(help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_f065d0_idx'), models.Index(fields=['model_name', 'object_id'], name='activity_lo_model_n_8ff728_idx'), models.Index(fields=['action', '-timestamp'], name='activity_lo_action_f5c228_idx')],
            },
        ),
    ]
