# Generated by Django 4.2.30 on 2026-06-26 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID assigned by school.', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, help_text='Department (Science, Arts, Mathematics, etc.).', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job title (Senior Teacher, Head of Department, etc.).', max_length=100, null=True)),
                ('joining_date', models.DateField(help_text='Date when the teacher joined the school.')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('VISITING', 'Visiting')], default='FULL_TIME', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary (optional, private).', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('highest_qualification', models.CharField(blank=True, help_text='e.g. M.Sc. Computer Science, B.Ed.', max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Subject specialization (e.g. Physics, English Literature).', max_length=200, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Total years of teaching experience.')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account for salary transfer (private).', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account linked to this teacher.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
