# Generated by Django 5.2.17 on 2026-08-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_academicsession'),
        ('subjects', '0002_alter_enrollment_options_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='classes.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='classes.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='classes.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Allocation',
                'verbose_name_plural': 'Teacher Allocations',
                'db_table': 'teacher_allocations',
                'ordering': ['academic_session', 'school_class', 'section', 'subject'],
                'unique_together': {('academic_session', 'school_class', 'section', 'subject')},
            },
        ),
    ]
