"""
Root URL configuration for School Management System.
All app URLs are included here with a common /api/v1/ prefix.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Django admin panel
    path('admin/', admin.site.urls),

    # ─── API Version 1 (DRF with Routers) ─────────────────────────────────────
    # All REST API endpoints are automatically generated by DRF routers
    # See api/v1/routers.py for ViewSet registration
    path('api/v1/', include('api.v1.urls')),
]

# Serve media files in development (profile pictures, uploaded files)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
