# Generated by Django 4.2.30 on 2026-06-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_current_class_alter_student_section'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Midterm Fall 2024', max_length=150)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm Examination'), ('FINAL', 'Final Examination'), ('UNIT_TEST', 'Unit Test'), ('MONTHLY', 'Monthly Test'), ('CUSTOM', 'Custom Exam')], default='FINAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this exam currently active/ongoing?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_maximum_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'results',
                'ordering': ['exam', '-percentage'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='Automatically calculated.', max_length=5, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Marks',
                'verbose_name_plural': 'Marks',
                'db_table': 'marks',
                'ordering': ['exam', 'student', 'subject'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
