# Generated by Django 4.2.30 on 2026-07-11 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Midterm Fall 2024', max_length=150)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm Examination'), ('FINAL', 'Final Examination'), ('UNIT_TEST', 'Unit Test'), ('MONTHLY', 'Monthly Test'), ('QUIZ', 'Quiz'), ('PRACTICAL', 'Practical'), ('CUSTOM', 'Custom Exam')], default='FINAL', max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Total marks for this exam.')),
                ('passing_marks', models.PositiveIntegerField(default=40, help_text='Minimum marks to pass.', validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_date', models.DateField(blank=True, help_text='Specific exam date (if single day).', null=True)),
                ('exam_time_start', models.TimeField(blank=True, null=True)),
                ('exam_time_end', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes.', null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Exam instructions/description.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this exam currently active/ongoing?')),
                ('is_published', models.BooleanField(default=False, help_text='If true, marks are visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.class')),
                ('subject', models.ForeignKey(help_text='Subject for this exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_maximum_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'results',
                'ordering': ['exam', '-percentage'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33.0, max_digits=6)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='Automatically calculated.', max_length=5, null=True)),
                ('is_passed', models.BooleanField(default=False, help_text='Pass/Fail status.')),
                ('remarks', models.TextField(blank=True, help_text='Teacher remarks.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='subjects.subject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_marks', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Marks',
                'verbose_name_plural': 'Marks',
                'db_table': 'marks',
                'ordering': ['exam', 'student__user__first_name'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
