# Generated by Django 4.2.30 on 2026-06-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0002_alter_student_current_class_alter_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject (e.g. Mathematics, English).', max_length=100)),
                ('code', models.CharField(help_text='Unique subject code (e.g. MATH-101).', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('OPTIONAL', 'Optional')], default='COMPULSORY', max_length=20)),
                ('credits', models.PositiveIntegerField(default=1, help_text='Credit hours for the subject.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(help_text='The class this subject is taught in.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class')),
                ('teacher', models.ForeignKey(blank=True, help_text='The teacher assigned to teach this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['school_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2023-2024', max_length=20)),
                ('roll_number', models.CharField(blank=True, help_text='Roll number for this specific enrollment.', max_length=20, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the student currently active in this enrollment?')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-academic_year', 'school_class', 'section'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
