# Generated by Django 4.2.30 on 2026-07-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title.', max_length=200)),
                ('content', models.TextField(help_text='Announcement content/body.')),
                ('target_audience', models.CharField(choices=[('ALL', 'Everyone'), ('TEACHERS', 'Teachers Only'), ('STUDENTS', 'Students Only'), ('SPECIFIC_CLASS', 'Specific Class'), ('SPECIFIC_SECTION', 'Specific Section')], default='ALL', help_text='Who should see this announcement?', max_length=20)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important announcement.')),
                ('is_published', models.BooleanField(default=True, help_text='Published announcements are visible to users.')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (PDF, image, etc.)', null=True, upload_to='announcements/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Announcement auto-hides after this date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(help_text='Admin/User who published this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, help_text="Select class if audience is 'Specific Class' or 'Specific Section'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class')),
                ('target_section', models.ForeignKey(blank=True, help_text="Select section if audience is 'Specific Section'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.section')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-published_at'],
            },
        ),
    ]
