# Generated by Django 4.2.30 on 2026-06-27 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL', 'Everyone'), ('TEACHERS', 'Teachers Only'), ('STUDENTS', 'Students Only'), ('SPECIFIC_CLASS', 'Specific Class')], default='ALL', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or image attachment.', null=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, help_text="Select class if audience is 'Specific Class'", null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
