# Generated by Django 4.2.30 on 2026-06-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class name (e.g. Grade 9, KG, A-Level Year 1).', max_length=100, unique=True)),
                ('numeric_grade', models.PositiveIntegerField(blank=True, help_text='Numeric grade level for sorting (1-12). Leave blank for KG/Pre-KG.', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the class.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive classes won't appear in dropdowns.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='The main teacher responsible for this class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['numeric_grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name (e.g. A, B, C, Blue, Red).', max_length=10)),
                ('room_number', models.CharField(blank=True, help_text='Physical classroom number (e.g. Room 101).', max_length=20, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=40, help_text='Maximum number of students allowed in this section.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(help_text='The class this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.class')),
                ('section_teacher', models.ForeignKey(blank=True, help_text='The homeroom teacher for this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sections', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['school_class', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
