# Generated by Django 5.2.17 on 2026-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name (e.g. 2026-2027, 2027-2028)', max_length=50, unique=True)),
                ('start_date', models.DateField(help_text='Start date of session')),
                ('end_date', models.DateField(help_text='End date of session')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active session. Only one session can be current.')),
                ('is_active', models.BooleanField(default=True, help_text='Active sessions allow new transactions and enrollments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'db_table': 'academic_sessions',
                'ordering': ['-start_date'],
            },
        ),
    ]
