# Generated by Django 4.2.30 on 2026-06-26 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique admission/roll number assigned by school.', max_length=20, unique=True)),
                ('current_class', models.CharField(blank=True, help_text='Will be ForeignKey to Class model in Module 3.', max_length=50, null=True)),
                ('section', models.CharField(blank=True, help_text='Will be ForeignKey to Section model in Module 3.', max_length=10, null=True)),
                ('admission_date', models.DateField(help_text='Date when the student was admitted to the school.')),
                ('roll_number', models.CharField(blank=True, help_text='Roll number within the class.', max_length=20, null=True)),
                ('date_of_birth', models.DateField(help_text="Student's date of birth.")),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('address', models.TextField(help_text='Residential address of the student.')),
                ('photo', models.ImageField(blank=True, help_text='Student photo (optional).', null=True, upload_to='students/photos/')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, help_text='Emergency guardian (if different from parents).', max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_relation', models.CharField(blank=True, help_text='Relationship of guardian to student (Uncle, Aunt, etc.).', max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Primary emergency contact number.', max_length=20, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any known medical conditions or allergies.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('EXPELLED', 'Expelled'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account linked to this student.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
            },
        ),
    ]
