# Generated by Django 4.2.30 on 2026-06-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text='The class the student is currently enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section the student is currently enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.section'),
        ),
    ]
