# Generated by Django 5.2.17 on 2026-08-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_academicsession'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Application / Admission Number', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('APPROVED', 'Approved & Enrolled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='classes.academicsession')),
                ('created_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_record', to='students.student')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='classes.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='classes.section')),
            ],
            options={
                'verbose_name': 'Student Admission',
                'verbose_name_plural': 'Student Admissions',
                'db_table': 'student_admissions',
                'ordering': ['-admission_date'],
            },
        ),
    ]
