# Generated by Django 5.2.17 on 2026-08-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_academicsession'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='classes.academicsession'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='classes.academicsession'),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2026-2027', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2026-2027', max_length=20, null=True),
        ),
    ]
