# Generated by Django 4.2.30 on 2026-09-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='is_void',
            field=models.BooleanField(default=False, help_text='If True, this payment was canceled/voided.'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g., "September Tuition", "Arrears", "Sibling Discount"', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Can be negative for discounts', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(blank=True, help_text='Optional link to a formal fee category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice')),
            ],
            options={
                'verbose_name': 'Fee Invoice Item',
                'verbose_name_plural': 'Fee Invoice Items',
                'db_table': 'fee_invoice_items',
                'ordering': ['created_at'],
            },
        ),
    ]
